import Link from 'next/link'
import { ArrowRight, Brain, CalendarDays, CheckCircle2, Compass, MessageCircle, RefreshCw, Sparkles, Target, Trophy } from 'lucide-react'
import type { StudentDashboardData } from '@/lib/student-data'

type Props = { student: StudentDashboardData }
const icons = [MessageCircle, RefreshCw, Brain, CheckCircle2, Sparkles]
function label(status:string){const s=status.toLowerCase(); if(s.includes('strong'))return 'STRONG'; if(s.includes('improv'))return 'GROWING'; if(s.includes('focus'))return 'NEXT FOCUS'; return 'IN PROGRESS'}

export function AdultLearnerJourneyDashboard({student}:Props){
 const p=student.canonicalProjection
 const attended=student.attendanceOverview.filter(x=>x.status==='present')
 return <main className="min-h-screen bg-[#f7fbff] text-[#0b2c5c]">
  <section className="relative overflow-hidden bg-gradient-to-br from-[#eef7ff] via-white to-[#fff2f3]">
   <div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#e60023]/10 blur-3xl"/><div className="absolute -left-20 bottom-0 h-64 w-64 rounded-full bg-[#0057b8]/10 blur-3xl"/>
   <div className="relative mx-auto max-w-6xl px-4 py-6 sm:px-6 md:py-10">
    <div className="mb-6 flex items-center justify-between gap-4"><img src="/brand/prime-digital-hub-full-transparent.png" alt="Prime Digital Hub" className="h-auto w-40 sm:w-52"/><div className="rounded-full border border-blue-200 bg-white/90 px-4 py-2 text-xs font-bold shadow-sm">{attended.length} confirmed lessons • your learning journey</div></div>
    <div className="mb-5 inline-flex rounded-full bg-[#0b2c5c] px-4 py-2 text-xs font-bold uppercase tracking-[0.16em] text-white">Standalone Journey View • Plan B</div>
    <div className="grid items-center gap-7 lg:grid-cols-[1.25fr_.75fr]"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-[#e60023]">My English Journey</p><h1 className="mt-3 max-w-4xl text-4xl font-black leading-[1.02] tracking-tight sm:text-5xl md:text-6xl">Hi, Cláudio.<span className="mt-2 block text-[#0057b8]">See what your English has already been doing.</span></h1><p className="mt-5 max-w-3xl text-base font-medium leading-7 text-slate-700 sm:text-lg">This is not just a list of topics. It is your learning journey: what you have discussed, the language that keeps returning, what is already strong and what we are sharpening next.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/action?studentEmail=claudio.bit%40gmail.com" className="inline-flex items-center gap-2 rounded-2xl bg-[#e60023] px-5 py-3 text-sm font-black text-white shadow-lg shadow-red-200"><Target className="h-4 w-4"/>OPEN MY NEXT MISSION<ArrowRight className="h-4 w-4"/></Link><div className="inline-flex items-center gap-2 rounded-2xl border border-blue-200 bg-white px-5 py-3 text-sm font-bold shadow-sm"><CalendarDays className="h-4 w-4 text-[#0057b8]"/>{student.attendanceRate}</div></div></div>
     <div className="relative mx-auto w-full max-w-sm"><div className="rounded-[34px] border border-blue-200 bg-[#0b2c5c] p-6 text-white shadow-2xl"><div className="flex items-center justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><Trophy className="h-8 w-8 text-yellow-300"/></div><span className="rounded-full bg-emerald-400/20 px-3 py-1 text-xs font-extrabold text-emerald-200">KEEP MOVING</span></div><p className="mt-6 text-xs font-bold uppercase tracking-[0.2em] text-blue-200">WHERE I AM NOW</p><p className="mt-2 text-2xl font-black">{student.currentLevel}</p><p className="mt-5 text-sm leading-6 text-blue-100">Current direction: <strong className="text-white">{student.targetLevel}</strong>. The goal is greater precision, organization and automaticity without losing the depth of your ideas.</p></div></div>
    </div>
   </div>
  </section>
  <div className="mx-auto max-w-6xl space-y-8 px-4 py-9 sm:px-6">
   <section className="grid gap-4 md:grid-cols-3"><article className="rounded-[28px] border border-blue-200 bg-white p-5 shadow-sm md:col-span-2"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-100 text-[#0057b8]"><Sparkles className="h-6 w-6"/></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#0057b8]">WHAT CHANGED?</p><h2 className="text-xl font-black">The film of your journey</h2></div></div><h3 className="mt-5 text-2xl font-black">{p.whatChanged?.title}</h3><p className="mt-4 text-sm leading-7 text-slate-700">{p.whatChanged?.summary}</p><div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#0057b8]">HUMAN EVIDENCE</p><p className="mt-2 text-sm leading-6 text-slate-700">The evidence records what happened. Teacher interpretation connects the points. A single lesson does not need to prove progress by itself to belong to the story.</p></div></article><article className="rounded-[28px] bg-[#e60023] p-5 text-white shadow-lg shadow-red-100"><Compass className="h-8 w-8"/><p className="mt-5 text-xs font-black uppercase tracking-[0.18em] text-red-100">YOUR DIRECTION</p><h2 className="mt-2 text-2xl font-black">Where are we going?</h2><p className="mt-3 text-sm leading-7 text-red-50">{p.currentState.objective.value}</p></article></section>
   <section><p className="text-xs font-black uppercase tracking-[0.2em] text-[#e60023]">YOUR LEARNING SIGNALS</p><h2 className="mt-1 text-3xl font-black">What is visible now</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{student.progressTracker.map((x,i)=>{const I=icons[i%icons.length];return <article key={x.id} className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#eef7ff] text-[#0057b8]"><I className="h-5 w-5"/></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-black uppercase text-emerald-800">{label(x.status)}</span></div><h3 className="mt-4 text-lg font-black">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{x.insight}</p></article>})}</div></section>
   <section className="rounded-[32px] border border-blue-200 bg-gradient-to-br from-[#0b2c5c] to-[#0057b8] p-5 text-white shadow-xl md:p-7"><div className="flex items-center gap-3"><CalendarDays className="h-6 w-6 text-cyan-200"/><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-200">RECENT • CONFIRMED LESSONS</p><h2 className="text-2xl font-black">Your story so far</h2></div></div><div className="mt-6 grid gap-3">{attended.map((x,i)=><article key={x.id} className="rounded-2xl border border-white/15 bg-white/10 p-4"><p className="text-xs font-bold text-cyan-200">CHAPTER {i+1} • {x.date}</p><h3 className="mt-1 font-black">{x.title}</h3><p className="mt-2 text-sm leading-6 text-blue-50">{x.summary}</p></article>)}</div></section>
   {student.historicalMemory.length?<section className="rounded-[30px] border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">MEMORY • PRESERVED, NOT ATTENDANCE</p>{student.historicalMemory.map(x=><article key={x.id} className="mt-4"><h2 className="text-xl font-black">{x.title}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{x.evidence}</p><p className="mt-2 text-xs leading-5 text-slate-500">{x.note}</p></article>)}</section>:null}
   <section className="grid gap-4 md:grid-cols-2"><article className="rounded-[28px] border border-blue-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#0057b8]">TEACHER INSIGHT</p><p className="mt-4 text-base leading-7 text-slate-700">{student.teacherFeedback[0]?.body}</p></article><article className="rounded-[28px] bg-[#0b2c5c] p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-200">WHAT MATTERS NEXT</p><h2 className="mt-2 text-2xl font-black">{p.nextAction?.title}</h2><p className="mt-3 text-sm leading-7 text-blue-50">{p.nextAction?.description}</p><Link href="/dashboard/action?studentEmail=claudio.bit%40gmail.com" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black text-[#0b2c5c]">OPEN MISSION <ArrowRight className="h-4 w-4"/></Link></article></section>
  </div>
 </main>
}